name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Upload files
      uses: hannut91/aws-cli@v1.18.178
      with:
        args: s3 sync . s3://accord-frontdoor/ --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCORDCI_AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCORDCI_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

