name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: action/checkout@v2
    - name: Install aws cli
      uses: isbang/setup-awscli@v0.1.0

