name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: nelonoel/branch-name@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Get container
      run: docker pull ghcr.io/uvarc/onramp-builder
    - name: Run container
      run: docker run -e AWS_ACCESS_KEY_ID=${{ secrets.ACCORDCI_AWS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.ACCORDCI_AWS_SECRET_ACCESS_KEY }} ghcr.io/uvarc/onramp-builder /build.sh
 