name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete --exclude ".git/*" --exclude ".github/*"
      env:
        AWS_S3_BUCKET: 'accord-frontdoor'
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCORDCI_AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCORDCI_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: ''
