name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      use: action/checkout@v2
    - name: Install aws cli
      use: isbang/setup-awscli@v0.1.0

