name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Echo out an ENV var
        uses: uvarc/awscli-action@v0.1
        run: echo ${{ACCORDCI_AWS_KEY_ID}}

