name: Upload and Publish

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get the action
        uses: uvarc/awscli-action@v0.1
      - name: Echo out a VAR
        run: echo ${{ secrets.ACCORDCI_AWS_KEY_ID }}

